#!/usr/bin/env bash
# Deploy veil_core + asp to Stellar testnet.
#
# Prerequisites:
#   - stellar CLI installed
#   - DEPLOYER env var set to the deployer's secret key
#   - Contracts built: contracts/target/wasm32v1-none/release/{veil_core,asp}.wasm
#
# Usage:
#   DEPLOYER=S... ./deployments/testnet-deploy.sh
#
# Outputs contract IDs to deployments/testnet.env for downstream scripts.

set -euo pipefail

NETWORK="testnet"
RPC="https://soroban-testnet.stellar.org"
PASSPHRASE="Test SDF Network ; September 2015"
WASM_DIR="contracts/target/wasm32v1-none/release"

if [ -z "${DEPLOYER:-}" ]; then
    echo "Using default deployer identity..."
    DEPLOYER="deployer"
fi

echo "=== Veil Protocol testnet deploy ==="

# 1. Deploy asp contract
echo "Deploying asp..."
ASP_ID=$(stellar contract deploy \
    --wasm "$WASM_DIR/asp.wasm" \
    --source "$DEPLOYER" \
    --rpc-url "$RPC" \
    --network-passphrase "$PASSPHRASE" 2> /dev/null | tail -1)
echo "ASP contract: $ASP_ID"

# 2. Deploy veil_core contract
echo "Deploying veil_core..."
CORE_ID=$(stellar contract deploy \
    --wasm "$WASM_DIR/veil_core.wasm" \
    --source "$DEPLOYER" \
    --rpc-url "$RPC" \
    --network-passphrase "$PASSPHRASE" 2> /dev/null | tail -1)
echo "VeilCore contract: $CORE_ID"

# 3. Get deployer public key
DEPLOYER_PUB=$(stellar keys address "$DEPLOYER" 2>/dev/null || echo "")
if [ -z "$DEPLOYER_PUB" ]; then
    # Derive from key if 'stellar keys address' doesn't work
    echo "WARN: could not derive deployer public key; set ADMIN manually"
    DEPLOYER_PUB="TODO"
fi

# 4. Write env file
mkdir -p deployments
cat > deployments/testnet.env <<EOF
# Generated by testnet-deploy.sh at $(date -u)
VEIL_CORE=$CORE_ID
ASP=$ASP_ID
ADMIN=$DEPLOYER_PUB
SOROBAN_RPC=$RPC
NETWORK=$NETWORK
PASSPHRASE="$PASSPHRASE"
EOF

echo ""
echo "Deployed. Config written to deployments/testnet.env"
echo ""
echo "Next steps:"
echo "  1. Initialize contracts:"
echo "     stellar contract invoke --id \$ASP --source \$DEPLOYER -- initialize --operator \$ADMIN"
echo "     stellar contract invoke --id \$VEIL_CORE --source \$DEPLOYER -- initialize --admin \$ADMIN"
echo "  2. Register asp as module in veil_core"
echo "  3. Set auditor pubkey"
echo "  4. Init vk with circuit-keys/dev/vk_deposit.bin"
echo "  5. Run e2e tests: source deployments/testnet.env && node e2e-tests/src/deposit.test.js"
